### ISSUE TITLE
multiple arguments to console.log prints duplicates

### ISSUE THREAD

**Issue by feross** [defunctzombie/zuul#127]
When I write:

```
console.log(1, 2, 3)
```

This gets printed:

```
1 2 3 2 3
```

**Comment by feross** [comment]
This also causes weird issues with the `debug` module.

```
var debug = require('debug')('simple-peer')
debug(1)
```

Produces:

```
simple-peer 1 +0ms 'color: lightseagreen' 'color: inherit' 1 'color: lightseagreen'
```

**Comment by feross** [comment]
This line seems to be the culprit:

https://github.com/defunctzombie/zuul/blob/28849c2c89a7c371c65adc875cc443de84ff9b36/frameworks/tape/client.js#L35

When you pass multiple arguments to console.log, this will fail because it iterates through the arguments and concats them to the first argument, effectively duplicating them.

How can we fix this? What is the purpose of this code?

**Comment by defunctzombie** [comment]
You can fix this by not using tape ;P

Honestly not sure what the purpose of that code is or where I originally got it from. Likely some example from substack, who knows.

I dislike tape because it overloads stdout and doesn't give a great interface to hook into test events. I am open to any suggestions here or improvements since I myself don't use tape.

**Comment by feross** [comment]
What do you use instead of tape?

**Comment by feross** [comment]
Sent a PR to fix the issue with tape.

**Comment by defunctzombie** [comment]
I use mocha.

Do I need to fix anything with zuul?

**Comment by feross** [comment]
I sent a PR to fix the issue I was seeing with tape. It's here:  https://github.com/defunctzombie/zuul/pull/128

**Comment by defunctzombie** [comment]
pushed it out in v1.16.5

**Comment by feross** [comment]
thanks!
